export const LOADING_PROGRESS_ACTION = 'LOADING_PROGRESS_ACTION';
export const CHOSEN_RUNNERS_ACTION = 'CHOSEN_RUNNERS_ACTION';
export const CHOSEN_RACE_ACTION = 'CHOSEN_RACE_ACTION';
export const END_INDEX_ACTION = 'END_INDEX_ACTION';
export const LOAD_MORE_PROGRESS_ACTION = 'LOAD_MORE_PROGRESS_ACTION';